/* MAIN */
export const FOOD_RECOGNITION_FETCH_PREDICTIONS = 'FOOD_RECOGNITION_FETCH_PREDICTIONS';
export const FOOD_RECOGNITION_FETCH_PREDICTIONS_PENDING = 'FOOD_RECOGNITION_FETCH_PREDICTIONS_PENDING';
export const FOOD_RECOGNITION_IMAGE_LINK_FIELD_UPDATED = 'FOOD_RECOGNITION_IMAGE_LINK_FIELD_UPDATED';
export const FOOD_RECOGNITION_IMAGE_LINK_FIELD_ERROR = 'FOOD_RECOGNITION_IMAGE_LINK_FIELD_ERROR';
export const FOOD_RECOGNITION_UPDATE_IMAGE_SRC = 'FOOD_RECOGNITION_UPDATE_IMAGE_SRC';

/* GET FOOD IMAGE */
export const FOOD_RECOGNITION_GET_RANDOM_IMAGE_PENDING = 'FOOD_RECOGNITION_GET_RANDOM_IMAGE_PENDING';
export const FOOD_RECOGNITION_GET_RANDOM_IMAGE_SUCCESS = 'FOOD_RECOGNITION_GET_RANDOM_IMAGE_SUCCESS';
export const FOOD_RECOGNITION_FORM_SET_IMAGE = 'FOOD_RECOGNITION_FORM_SET_IMAGE';

/* FORM STAGING */
export const FOOD_RECOGNITION_GO_TO_STAGE_1= 'FOOD_RECOGNITION_GO_TO_STAGE_1';
export const FOOD_RECOGNITION_GO_TO_STAGE_2 = 'FOOD_RECOGNITION_GO_TO_STAGE_2';
export const FOOD_RECOGNITION_GO_TO_STAGE_3 = 'FOOD_RECOGNITION_GO_TO_STAGE_3';

/* IMAGE GALLERY */
export const IMAGE_GALLERY_FETCH = 'IMAGE_GALLERY_FETCH';
export const IMAGE_GALLERY_TOGGLE_MODAL = 'IMAGE_GALLERY_TOGGLE_MODAL';
export const IMAGE_GALLERY_CLOSE_MODAL = 'IMAGE_GALLERY_CLOSE_MODAL';

/* RECIPES */
export const RECIPES_FETCH = 'RECIPES_FETCH';
export const RECIPES_TOGGLE_MODAL = 'RECIPES_TOGGLE_MODAL';